In [1]:
import pandas as pd
import numpy as np

In [2]:
horses = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv', na_values='?')
horses.columns = ['surgery?','Age','Hospital Number','rectal temperature','pulse','respiratory rate','temperature of extremities','peripheral pulse','mucous membranes','capillary refill time','pain','peristalsis','abdominal distension','nasogastric tube','nasogastric reflux','nasogastric reflux PH','rectal examination - feces','abdomen','packed cell volume','total protein','abdominocentesis appearance','abdomcentesis total protein','outcome','surgical lesion?','type of lesion_1','type of lesion_2','type of lesion_3','cp_data']
horses = horses[['surgery?','Age','rectal temperature','pulse','respiratory rate','temperature of extremities','pain','outcome']]
horse = horses.copy()
horse.head()

surgery?  Age  rectal temperature  pulse  respiratory rate  \
0       1.0    1                39.2   88.0              20.0   
1       2.0    1                38.3   40.0              24.0   
2       1.0    9                39.1  164.0              84.0   
3       2.0    1                37.3  104.0              35.0   
4       2.0    1                 NaN    NaN               NaN   

   temperature of extremities  pain  outcome  
0                         NaN   3.0      3.0  
1                         1.0   3.0      1.0  
2                         4.0   2.0      2.0  
3                         NaN   NaN      2.0  
4                         2.0   2.0      1.0

In [3]:
horse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   surgery?                    298 non-null    float64
 1   Age                         299 non-null    int64  
 2   rectal temperature          239 non-null    float64
 3   pulse                       275 non-null    float64
 4   respiratory rate            241 non-null    float64
 5   temperature of extremities  243 non-null    float64
 6   pain                        244 non-null    float64
 7   outcome                     298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.8 KB


In [4]:
horse.isna().sum()

surgery?                       1
Age                            0
rectal temperature            60
pulse                         24
respiratory rate              58
temperature of extremities    56
pain                          55
outcome                        1
dtype: int64

In [5]:
round(horse.isna().mean()*100, 2)

surgery?                       0.33
Age                            0.00
rectal temperature            20.07
pulse                          8.03
respiratory rate              19.40
temperature of extremities    18.73
pain                          18.39
outcome                        0.33
dtype: float64

In [6]:
#Т.к у столбец с качественными данными и имеет всего два знаечния, ищем только моду
print(horse['surgery?'].mode()[0])

1.0


In [7]:
#Т.к у столбец с качественными данными и имеет всего два знаечния, ищем только моду
print(horse['Age'].mode()[0])

1


In [8]:
print(horse['rectal temperature'].mean())
print(horse['rectal temperature'].median())
print(horse['rectal temperature'].mode()[0])
print(horse['rectal temperature'].std())
print(horse['rectal temperature'].var())

38.166527196652716
38.2
38.0
0.7335083691537396
0.5380345276185787


In [9]:
print(horse['pulse'].mean())
print(horse['pulse'].median())
print(horse['pulse'].mode()[0])
print(horse['pulse'].std())
print(horse['pulse'].var())

71.93454545454546
64.0
48.0
28.68052200365475
822.5723424021243


In [10]:
print(horse['respiratory rate'].mean())
print(horse['respiratory rate'].median())
print(horse['respiratory rate'].mode()[0])
print(horse['respiratory rate'].std())
print(horse['respiratory rate'].var())

30.42738589211618
24.0
20.0
17.67825633053121
312.5207468879668


In [11]:
#Т.к у столбец с качественными данными, ищем только моду
print(horse['temperature of extremities'].mode()[0])

3.0


In [12]:
#Т.к у столбец с качественными данными, ищем только моду
print(horse['pain'].mode()[0])


3.0


In [13]:
#Т.к у столбец с качественными данными, ищем только моду
print(horse['outcome'].mode()[0])

1.0


In [14]:
horse[horse['surgery?'].isna()]

surgery?  Age  rectal temperature  pulse  respiratory rate  \
131       NaN    1                38.0   48.0              20.0   

     temperature of extremities  pain  outcome  
131                         3.0   4.0      NaN

In [15]:
#Т.к лошадь молодая, скорее всего, она выжила, а из-за сильной боли, скорее всего, ей сделали операцию
horse.loc[horse['surgery?'].isna(), 'outcome'] = 1

In [16]:
horse.loc[horse['surgery?'].isna(), 'surgery?'] = 1

In [17]:
horse['Age'].unique()

array([1, 9], dtype=int64)

9 выглядит как техническая ошибка и должна быть заменена на 2 судя по описанию столбца

In [18]:
horse.loc[horse['Age'] == 9] = 2

In [19]:
horse[horse['rectal temperature'].isna()]

surgery?  Age  rectal temperature  pulse  respiratory rate  \
4         2.0    1                 NaN    NaN               NaN   
6         1.0    1                 NaN   60.0               NaN   
7         2.0    1                 NaN   80.0              36.0   
27        1.0    1                 NaN    NaN               NaN   
33        1.0    1                 NaN  100.0              30.0   
34        2.0    1                 NaN  104.0              24.0   
39        1.0    1                 NaN   88.0               NaN   
42        1.0    1                 NaN  120.0               NaN   
44        2.0    1                 NaN  120.0               NaN   
51        2.0    1                 NaN    NaN               NaN   
55        1.0    1                 NaN    NaN               NaN   
56        1.0    1                 NaN   64.0              36.0   
57        1.0    1                 NaN    NaN              20.0   
58        2.0    1                 NaN   96.0               NaN   
64        1.0    1                 NaN   60.0              36.0   
67        2.0    1                 NaN   52.0              16.0   
77        1.0    1                 NaN    NaN               NaN   
85        1.0    1                 NaN   88.0              40.0   
86        2.0    1                 NaN   40.0              16.0   
92        2.0    1                 NaN    NaN               NaN   
95        2.0    1                 NaN   84.0              36.0   
100       1.0    1                 NaN   60.0              20.0   
104       1.0    1                 NaN   70.0              36.0   
109       1.0    1                 NaN   70.0              16.0   
111       1.0    1                 NaN   40.0               NaN   
114       2.0    1                 NaN    NaN              40.0   
133       1.0    1                 NaN  100.0               NaN   
135       1.0    1                 NaN    NaN               NaN   
141       1.0    1                 NaN  120.0               NaN   
144       2.0    1                 NaN   80.0              32.0   
151       1.0    1                 NaN  100.0               NaN   
158       2.0    1                 NaN    NaN              12.0   
159       1.0    1                 NaN    NaN               NaN   
166       2.0    1                 NaN   44.0              24.0   
168       1.0    1                 NaN   65.0              24.0   
172       1.0    1                 NaN  104.0               NaN   
173       2.0    1                 NaN    NaN               NaN   
174       1.0    1                 NaN    NaN               NaN   
176       1.0    1                 NaN   68.0              14.0   
177       1.0    1                 NaN   60.0              30.0   
192       1.0    1                 NaN   60.0              48.0   
206       1.0    1                 NaN    NaN               NaN   
215       2.0    1                 NaN    NaN               NaN   
218       1.0    1                 NaN   52.0              28.0   
221       1.0    1                 NaN  112.0              13.0   
241       1.0    1                 NaN   36.0              32.0   
244       2.0    1                 NaN   96.0               NaN   
252       2.0    1                 NaN  112.0              24.0   
253       1.0    1                 NaN   80.0               NaN   
264       2.0    1                 NaN   56.0              68.0   
271       1.0    1                 NaN  100.0              30.0   
273       1.0    1                 NaN   76.0               NaN   
281       1.0    1                 NaN   70.0              16.0   
287       1.0    1                 NaN    NaN               NaN   
292       1.0    1                 NaN   78.0              24.0   
294       1.0    1                 NaN  120.0              70.0   

     temperature of extremities  pain  outcome  
4                           2.0   2.0      1.0  
6                           3.0   NaN      2.0  
7                           3.0   4.0 

Так как rectal temperature коррелирует с temperature of extremities, то заменим пропуски следующим образом: где temperature of extremities = 1, 3 или 4, то rectal temperature = 37.8, где temperature of extremities = 2, то ставим медианную температуру. Где оба значения не заполнены - удалим их

In [20]:
horse = horse.loc[~((horse['rectal temperature'].isna()) & (horse['temperature of extremities'].isna()))]
horse

surgery?  Age  rectal temperature  pulse  respiratory rate  \
0         1.0    1                39.2   88.0              20.0   
1         2.0    1                38.3   40.0              24.0   
2         2.0    2                 2.0    2.0               2.0   
3         2.0    1                37.3  104.0              35.0   
4         2.0    1                 NaN    NaN               NaN   
..        ...  ...                 ...    ...               ...   
294       1.0    1                 NaN  120.0              70.0   
295       2.0    1                37.2   72.0              24.0   
296       1.0    1                37.5   72.0              30.0   
297       1.0    1                36.5  100.0              24.0   
298       1.0    1                37.2   40.0              20.0   

     temperature of extremities  pain  outcome  
0                           NaN   3.0      3.0  
1                           1.0   3.0      1.0  
2                           2.0   2.0      2.0  
3                           NaN   NaN      2.0  
4                           2.0   2.0      1.0  
..                          ...   ...      ...  
294                         4.0   2.0      3.0  
295                         3.0   4.0      3.0  
296                         4.0   4.0      2.0  
297                         3.0   3.0      1.0  
298                         NaN   NaN      3.0  

[287 rows x 8 columns]

In [21]:
horse.loc[((horse['rectal temperature'].isna()) & (horse['temperature of extremities'] != 2)), 'rectal temperature'] = 37.8

In [22]:
horse.loc[((horse['rectal temperature'].isna()) & (horse['temperature of extremities'] == 2)), 'rectal temperature'] = horses['rectal temperature'].median()

In [23]:
horse[horse['pulse'].isna()]

surgery?  Age  rectal temperature  pulse  respiratory rate  \
4         2.0    1                38.2    NaN               NaN   
51        2.0    1                37.8    NaN               NaN   
57        1.0    1                37.8    NaN              20.0   
77        1.0    1                37.8    NaN               NaN   
82        1.0    1                38.0    NaN              24.0   
92        2.0    1                37.8    NaN               NaN   
114       2.0    1                37.8    NaN              40.0   
116       2.0    1                39.5    NaN               NaN   
125       1.0    1                38.7    NaN               NaN   
135       1.0    1                37.8    NaN               NaN   
150       1.0    1                39.3    NaN               NaN   
158       2.0    1                37.8    NaN              12.0   
173       2.0    1                37.8    NaN               NaN   
181       1.0    1                38.0    NaN              24.0   
203       1.0    1                39.2    NaN              23.0   

     temperature of extremities  pain  outcome  
4                           2.0   2.0      1.0  
51                          1.0   1.0      1.0  
57                          4.0   5.0      2.0  
77                          3.0   5.0      2.0  
82                          3.0   5.0      2.0  
92                          3.0   5.0      2.0  
114                         3.0   3.0      1.0  
116                         3.0   3.0      3.0  
125                         3.0   5.0      1.0  
135                         3.0   5.0      2.0  
150                         4.0   4.0      2.0  
158                         1.0   2.0      1.0  
173                         3.0   4.0      2.0  
181                         3.0   5.0      2.0  
203                         3.0   4.0      1.0

Пульс связан с частотой дыхания. Сделаем замену следующим образом: где оба значения не заполнены - удалим их, где частота дыхания больше 10, ставим медианный пульс, где меньше 10 - 30

In [24]:
horse = horse.loc[~((horse['pulse'].isna()) & (horse['respiratory rate'].isna()))]
horse

surgery?  Age  rectal temperature  pulse  respiratory rate  \
0         1.0    1                39.2   88.0              20.0   
1         2.0    1                38.3   40.0              24.0   
2         2.0    2                 2.0    2.0               2.0   
3         2.0    1                37.3  104.0              35.0   
5         1.0    1                37.9   48.0              16.0   
..        ...  ...                 ...    ...               ...   
294       1.0    1                37.8  120.0              70.0   
295       2.0    1                37.2   72.0              24.0   
296       1.0    1                37.5   72.0              30.0   
297       1.0    1                36.5  100.0              24.0   
298       1.0    1                37.2   40.0              20.0   

     temperature of extremities  pain  outcome  
0                           NaN   3.0      3.0  
1                           1.0   3.0      1.0  
2                           2.0   2.0      2.0  
3                           NaN   NaN      2.0  
5                           1.0   3.0      1.0  
..                          ...   ...      ...  
294                         4.0   2.0      3.0  
295                         3.0   4.0      3.0  
296                         4.0   4.0      2.0  
297                         3.0   3.0      1.0  
298                         NaN   NaN      3.0  

[278 rows x 8 columns]

In [25]:
horse.loc[((horse['pulse'].isna()) & (horse['respiratory rate'] > 10)), 'pulse'] = horses['pulse'].median()

In [26]:
horse.loc[((horse['pulse'].isna()) & (horse['respiratory rate'] <= 10)), 'pulse'] = 30

In [27]:
horse[horse['respiratory rate'].isna()]

surgery?  Age  rectal temperature  pulse  respiratory rate  \
6         1.0    1                37.8   60.0               NaN   
28        2.0    1                37.7   48.0               NaN   
31        1.0    1                37.2   60.0               NaN   
36        1.0    1                37.8   72.0               NaN   
37        2.0    1                38.6   52.0               NaN   
39        1.0    1                37.8   88.0               NaN   
42        1.0    1                37.8  120.0               NaN   
44        2.0    1                37.8  120.0               NaN   
49        2.0    1                38.6   46.0               NaN   
58        2.0    1                37.8   96.0               NaN   
60        2.0    1                38.5   60.0               NaN   
65        2.0    1                37.9   72.0               NaN   
71        1.0    1                37.7   56.0               NaN   
80        1.0    1                37.3   40.0               NaN   
111       1.0    1                38.2   40.0               NaN   
128       1.0    1                38.4   49.0               NaN   
133       1.0    1                37.8  100.0               NaN   
136       1.0    1                38.0   48.0               NaN   
137       2.0    1                38.0   56.0               NaN   
141       1.0    1                37.8  120.0               NaN   
145       1.0    1                38.2   48.0               NaN   
147       1.0    1                38.3  132.0               NaN   
151       1.0    1                37.8  100.0               NaN   
163       1.0    1                38.7   76.0               NaN   
172       1.0    1                37.8  104.0               NaN   
178       2.0    1                38.5  100.0               NaN   
187       1.0    1                38.5   60.0               NaN   
200       1.0    1                38.5   86.0               NaN   
204       2.0    1                38.5  100.0               NaN   
237       2.0    1                36.1   88.0               NaN   
244       2.0    1                37.8   96.0               NaN   
248       2.0    1                38.2   48.0               NaN   
253       1.0    1                37.8   80.0               NaN   
255       1.0    1                37.5   72.0               NaN   
270       1.0    1                37.7   80.0               NaN   
280       2.0    1                40.0   78.0               NaN   
283       2.0    1                38.5   54.0               NaN   

     temperature of extremities  pain  outcome  
6                           3.0   NaN      2.0  
28                          2.0   1.0      1.0  
31                          2.0   3.0      1.0  
36                          NaN   5.0      1.0  
37                          1.0   3.0      1.0  
39                          3.0   5.0      2.0  
42                          3.0   4.0      3.0  
44                          4.0   5.0      2.0  
49                          1.0   1.0      1.0  
58                          3.0   5.0      2.0  
60                          2.0   1.0      1.0  
65                          1.0   3.0      1.0  
71                          NaN   NaN      2.0  
80                          NaN   2.0      1.0  
111                         2.0   1.0      1.0  
128                         NaN   NaN      1.0  
133                         3.0   5.0      2.0  
136                         1.0   1.0      1.0  
137                         1.0   1.0      1.0  
141                         4.0   5.0      2.0  
145                         1.0   3.0      1.0  
147                         NaN   2.0      1.0  
151                         3.0   NaN      1.0  
163                         1.0   3.0      1.0  
172                         3.0   2.0      2.0  
178                         3.0   4.0      3.0  
187                         1.0   NaN      1.0  
200                         1.0   4.0      2.0  
204                         3.0   4.0

Видим, что у всех незаполненных значений respiratory rate пульс выше нормы, заменим на медианное значение

In [28]:
horse.loc[horse['respiratory rate'].isna(), 'respiratory rate'] = horses['respiratory rate'].median()

In [29]:
horse[horse['temperature of extremities'].isna()]

surgery?  Age  rectal temperature  pulse  respiratory rate  \
0         1.0    1                39.2   88.0              20.0   
3         2.0    1                37.3  104.0              35.0   
16        2.0    1                37.5   48.0              24.0   
24        2.0    1                37.8   60.0              42.0   
35        2.0    1                38.3  112.0              16.0   
36        1.0    1                37.8   72.0              24.0   
52        2.0    1                38.6   40.0              20.0   
71        1.0    1                37.7   56.0              24.0   
80        1.0    1                37.3   40.0              24.0   
89        2.0    1                38.0   52.0              16.0   
94        1.0    1                37.3   48.0              20.0   
105       1.0    1                38.3   52.0              96.0   
112       1.0    1                36.8   60.0              28.0   
120       1.0    1                38.3   80.0              40.0   
127       1.0    1                37.4   84.0              20.0   
128       1.0    1                38.4   49.0              24.0   
129       1.0    1                37.8   30.0              12.0   
140       2.0    1                36.0   42.0              30.0   
147       1.0    1                38.3  132.0              24.0   
148       2.0    1                38.7   48.0              24.0   
160       1.0    1                38.3   42.0              24.0   
164       1.0    1                39.4  120.0              48.0   
180       2.0    1                37.8   48.0              14.0   
189       1.0    1                37.1   40.0               8.0   
201       1.0    1                37.5   48.0              40.0   
209       1.0    1                37.9   68.0              20.0   
216       1.0    1                38.0   76.0              18.0   
231       1.0    1                38.5   30.0              18.0   
238       1.0    1                38.1   70.0              22.0   
259       2.0    1                38.0   40.0              25.0   
262       1.0    1                37.1   75.0              36.0   
267       1.0    1                38.2   42.0              20.0   
279       1.0    1                38.6   48.0              12.0   
282       1.0    1                38.2   72.0              18.0   
288       1.0    1                38.0   50.0              36.0   
298       1.0    1                37.2   40.0              20.0   

     temperature of extremities  pain  outcome  
0                           NaN   3.0      3.0  
3                           NaN   NaN      2.0  
16                          NaN   NaN      1.0  
24                          NaN   NaN      1.0  
35                          NaN   NaN      3.0  
36                          NaN   5.0      1.0  
52                          NaN   NaN      1.0  
71                          NaN   NaN      2.0  
80                          NaN   2.0      1.0  
89                          NaN   2.0      1.0  
94                          NaN   3.0      1.0  
105                         NaN   NaN      1.0  
112                         NaN   NaN      2.0  
120                         NaN   4.0      3.0  
127                         NaN   2.0      3.0  
128                         NaN   NaN      1.0  
129                         NaN   NaN      2.0  
140                         NaN   NaN      2.0  
147                         NaN   2.0      1.0  
148                         NaN   1.0      1.0  
160                         NaN   NaN      2.0  
164                         NaN   NaN      3.0  
180                         NaN   3.0      1.0  
189                         NaN   3.0      1.0  
201                         NaN   NaN      3.0  
209                         NaN   2.0      2.0  
216                         NaN   NaN      1.0  
231                         NaN   NaN      1.0  
238                         NaN   5.0      3.0  
259                         NaN   4.0      1.0  
262   

Так как rectal temperature коррелирует с temperature of extremities, то заменим пропуски следующим образом: где rectal temperature от 37.6 до 38.0, то temperature of extremities = 1, если rectal temperature больше 38,0 то temperature of extremities = 2, если rectal temperature от 37.2 до 37.6, то temperature of extremities = 3, в остальном случае ставим 4

In [30]:
horse.loc[horse['rectal temperature'] > 38.0, 'temperature of extremities'] = 2

In [31]:
horse.loc[(horse['rectal temperature'] >= 37.6) & (horse['rectal temperature'] <= 38.0), 'temperature of extremities'] = 1

In [32]:
horse.loc[(horse['rectal temperature'] < 37.6) & (horse['rectal temperature'] >= 37.2), 'temperature of extremities'] = 3

In [33]:
horse.loc[horse['rectal temperature'] < 37.2, 'temperature of extremities'] = 4

In [34]:
horse[horse['pain'].isna()]

surgery?  Age  rectal temperature  pulse  respiratory rate  \
3         2.0    1                37.3  104.0              35.0   
6         1.0    1                37.8   60.0              24.0   
16        2.0    1                37.5   48.0              24.0   
18        2.0    1                39.4  110.0              35.0   
23        1.0    1                38.1   60.0              12.0   
24        2.0    1                37.8   60.0              42.0   
26        1.0    1                37.8   48.0              12.0   
35        2.0    1                38.3  112.0              16.0   
52        2.0    1                38.6   40.0              20.0   
67        2.0    1                37.8   52.0              16.0   
71        1.0    1                37.7   56.0              24.0   
93        2.0    1                37.5   48.0              30.0   
105       1.0    1                38.3   52.0              96.0   
112       1.0    1                36.8   60.0              28.0   
128       1.0    1                38.4   49.0              24.0   
129       1.0    1                37.8   30.0              12.0   
140       2.0    1                36.0   42.0              30.0   
151       1.0    1                37.8  100.0              24.0   
156       1.0    1                37.8   60.0              24.0   
160       1.0    1                38.3   42.0              24.0   
164       1.0    1                39.4  120.0              48.0   
169       2.0    1                37.5   44.0              20.0   
184       1.0    1                38.5  120.0              60.0   
185       1.0    1                39.3   64.0              90.0   
187       1.0    1                38.5   60.0              24.0   
194       2.0    1                38.0   44.0              12.0   
201       1.0    1                37.5   48.0              40.0   
207       1.0    1                37.8   88.0              80.0   
212       1.0    1                37.6   45.0              12.0   
216       1.0    1                38.0   76.0              18.0   
231       1.0    1                38.5   30.0              18.0   
233       2.0    1                37.5   48.0              30.0   
242       1.0    1                38.4   92.0              20.0   
256       1.0    1                38.7   96.0              28.0   
267       1.0    1                38.2   42.0              20.0   
268       1.0    1                39.3   64.0              90.0   
282       1.0    1                38.2   72.0              18.0   
292       1.0    1                37.8   78.0              24.0   
298       1.0    1                37.2   40.0              20.0   

     temperature of extremities  pain  outcome  
3                           3.0   NaN      2.0  
6                           1.0   NaN      2.0  
16                          3.0   NaN      1.0  
18                          2.0   NaN      1.0  
23                          2.0   NaN      1.0  
24                          1.0   NaN      1.0  
26                          1.0   NaN      1.0  
35                          2.0   NaN      3.0  
52                          2.0   NaN      1.0  
67                          1.0   NaN      1.0  
71                          1.0   NaN      2.0  
93                          3.0   NaN      1.0  
105                         2.0   NaN      1.0  
112                         4.0   NaN      2.0  
128                         2.0   NaN      1.0  
129                         1.0   NaN      2.0  
140                         4.0   NaN      2.0  
151                         1.0   NaN      1.0  
156                         1.0   NaN      3.0  
160                         2.0   NaN      2.0  
164                         2.0   NaN      3.0  
169                         3.0   NaN      1.0  
184                         2.0   NaN      1.0  
185                         2.0   NaN      1.0  
187                         2.0   NaN      1.0  
194                         1.0   NaN      1.0  
2

Так как уровень боли достаточно субъективен для оценки, заменим на моду

In [35]:
horse.loc[horse['pain'].isna(), 'pain'] = horses['pain'].mode()[0]

In [36]:
#Все пустые значения заменили
horse.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 278 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   surgery?                    278 non-null    float64
 1   Age                         278 non-null    int64  
 2   rectal temperature          278 non-null    float64
 3   pulse                       278 non-null    float64
 4   respiratory rate            278 non-null    float64
 5   temperature of extremities  278 non-null    float64
 6   pain                        278 non-null    float64
 7   outcome                     278 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 19.5 KB
